/*
Copyright 2019 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/alibaba/kubedl/api/xdl/v1alpha1"
	scheme "github.com/alibaba/kubedl/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// XDLJobsGetter has a method to return a XDLJobInterface.
// A group's client should implement this interface.
type XDLJobsGetter interface {
	XDLJobs(namespace string) XDLJobInterface
}

// XDLJobInterface has methods to work with XDLJob resources.
type XDLJobInterface interface {
	Create(*v1alpha1.XDLJob) (*v1alpha1.XDLJob, error)
	Update(*v1alpha1.XDLJob) (*v1alpha1.XDLJob, error)
	UpdateStatus(*v1alpha1.XDLJob) (*v1alpha1.XDLJob, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.XDLJob, error)
	List(opts v1.ListOptions) (*v1alpha1.XDLJobList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.XDLJob, err error)
	XDLJobExpansion
}

// xDLJobs implements XDLJobInterface
type xDLJobs struct {
	client rest.Interface
	ns     string
}

// newXDLJobs returns a XDLJobs
func newXDLJobs(c *XdlV1alpha1Client, namespace string) *xDLJobs {
	return &xDLJobs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the xDLJob, and returns the corresponding xDLJob object, and an error if there is any.
func (c *xDLJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.XDLJob, err error) {
	result = &v1alpha1.XDLJob{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xdljobs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of XDLJobs that match those selectors.
func (c *xDLJobs) List(opts v1.ListOptions) (result *v1alpha1.XDLJobList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.XDLJobList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xdljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested xDLJobs.
func (c *xDLJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("xdljobs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a xDLJob and creates it.  Returns the server's representation of the xDLJob, and an error, if there is any.
func (c *xDLJobs) Create(xDLJob *v1alpha1.XDLJob) (result *v1alpha1.XDLJob, err error) {
	result = &v1alpha1.XDLJob{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("xdljobs").
		Body(xDLJob).
		Do().
		Into(result)
	return
}

// Update takes the representation of a xDLJob and updates it. Returns the server's representation of the xDLJob, and an error, if there is any.
func (c *xDLJobs) Update(xDLJob *v1alpha1.XDLJob) (result *v1alpha1.XDLJob, err error) {
	result = &v1alpha1.XDLJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("xdljobs").
		Name(xDLJob.Name).
		Body(xDLJob).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *xDLJobs) UpdateStatus(xDLJob *v1alpha1.XDLJob) (result *v1alpha1.XDLJob, err error) {
	result = &v1alpha1.XDLJob{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("xdljobs").
		Name(xDLJob.Name).
		SubResource("status").
		Body(xDLJob).
		Do().
		Into(result)
	return
}

// Delete takes name of the xDLJob and deletes it. Returns an error if one occurs.
func (c *xDLJobs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xdljobs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *xDLJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xdljobs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched xDLJob.
func (c *xDLJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.XDLJob, err error) {
	result = &v1alpha1.XDLJob{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("xdljobs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
