/*
Copyright 2019 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/alibaba/kubedl/api/xdl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeXDLJobs implements XDLJobInterface
type FakeXDLJobs struct {
	Fake *FakeXdlV1alpha1
	ns   string
}

var xdljobsResource = schema.GroupVersionResource{Group: "xdl.kubedl.io", Version: "v1alpha1", Resource: "xdljobs"}

var xdljobsKind = schema.GroupVersionKind{Group: "xdl.kubedl.io", Version: "v1alpha1", Kind: "XDLJob"}

// Get takes name of the xDLJob, and returns the corresponding xDLJob object, and an error if there is any.
func (c *FakeXDLJobs) Get(name string, options v1.GetOptions) (result *v1alpha1.XDLJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(xdljobsResource, c.ns, name), &v1alpha1.XDLJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.XDLJob), err
}

// List takes label and field selectors, and returns the list of XDLJobs that match those selectors.
func (c *FakeXDLJobs) List(opts v1.ListOptions) (result *v1alpha1.XDLJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(xdljobsResource, xdljobsKind, c.ns, opts), &v1alpha1.XDLJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.XDLJobList{ListMeta: obj.(*v1alpha1.XDLJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.XDLJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested xDLJobs.
func (c *FakeXDLJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(xdljobsResource, c.ns, opts))

}

// Create takes the representation of a xDLJob and creates it.  Returns the server's representation of the xDLJob, and an error, if there is any.
func (c *FakeXDLJobs) Create(xDLJob *v1alpha1.XDLJob) (result *v1alpha1.XDLJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(xdljobsResource, c.ns, xDLJob), &v1alpha1.XDLJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.XDLJob), err
}

// Update takes the representation of a xDLJob and updates it. Returns the server's representation of the xDLJob, and an error, if there is any.
func (c *FakeXDLJobs) Update(xDLJob *v1alpha1.XDLJob) (result *v1alpha1.XDLJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(xdljobsResource, c.ns, xDLJob), &v1alpha1.XDLJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.XDLJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeXDLJobs) UpdateStatus(xDLJob *v1alpha1.XDLJob) (*v1alpha1.XDLJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(xdljobsResource, "status", c.ns, xDLJob), &v1alpha1.XDLJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.XDLJob), err
}

// Delete takes name of the xDLJob and deletes it. Returns an error if one occurs.
func (c *FakeXDLJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(xdljobsResource, c.ns, name), &v1alpha1.XDLJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeXDLJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(xdljobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.XDLJobList{})
	return err
}

// Patch applies the patch and returns the patched xDLJob.
func (c *FakeXDLJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.XDLJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(xdljobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.XDLJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.XDLJob), err
}
