/*
Copyright 2019 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	xdlv1alpha1 "github.com/alibaba/kubedl/api/xdl/v1alpha1"
	versioned "github.com/alibaba/kubedl/client/clientset/versioned"
	internalinterfaces "github.com/alibaba/kubedl/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/alibaba/kubedl/client/listers/xdl/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// XDLJobInformer provides access to a shared informer and lister for
// XDLJobs.
type XDLJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.XDLJobLister
}

type xDLJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewXDLJobInformer constructs a new informer for XDLJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewXDLJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredXDLJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredXDLJobInformer constructs a new informer for XDLJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredXDLJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XdlV1alpha1().XDLJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.XdlV1alpha1().XDLJobs(namespace).Watch(options)
			},
		},
		&xdlv1alpha1.XDLJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *xDLJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredXDLJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *xDLJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&xdlv1alpha1.XDLJob{}, f.defaultInformer)
}

func (f *xDLJobInformer) Lister() v1alpha1.XDLJobLister {
	return v1alpha1.NewXDLJobLister(f.Informer().GetIndexer())
}
