/*
Copyright 2021 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/alibaba/kubedl/apis/training/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMarsJobs implements MarsJobInterface
type FakeMarsJobs struct {
	Fake *FakeTrainingV1alpha1
	ns   string
}

var marsjobsResource = schema.GroupVersionResource{Group: "training.kubedl.io", Version: "v1alpha1", Resource: "marsjobs"}

var marsjobsKind = schema.GroupVersionKind{Group: "training.kubedl.io", Version: "v1alpha1", Kind: "MarsJob"}

// Get takes name of the marsJob, and returns the corresponding marsJob object, and an error if there is any.
func (c *FakeMarsJobs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MarsJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(marsjobsResource, c.ns, name), &v1alpha1.MarsJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MarsJob), err
}

// List takes label and field selectors, and returns the list of MarsJobs that match those selectors.
func (c *FakeMarsJobs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MarsJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(marsjobsResource, marsjobsKind, c.ns, opts), &v1alpha1.MarsJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MarsJobList{ListMeta: obj.(*v1alpha1.MarsJobList).ListMeta}
	for _, item := range obj.(*v1alpha1.MarsJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested marsJobs.
func (c *FakeMarsJobs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(marsjobsResource, c.ns, opts))

}

// Create takes the representation of a marsJob and creates it.  Returns the server's representation of the marsJob, and an error, if there is any.
func (c *FakeMarsJobs) Create(ctx context.Context, marsJob *v1alpha1.MarsJob, opts v1.CreateOptions) (result *v1alpha1.MarsJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(marsjobsResource, c.ns, marsJob), &v1alpha1.MarsJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MarsJob), err
}

// Update takes the representation of a marsJob and updates it. Returns the server's representation of the marsJob, and an error, if there is any.
func (c *FakeMarsJobs) Update(ctx context.Context, marsJob *v1alpha1.MarsJob, opts v1.UpdateOptions) (result *v1alpha1.MarsJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(marsjobsResource, c.ns, marsJob), &v1alpha1.MarsJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MarsJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMarsJobs) UpdateStatus(ctx context.Context, marsJob *v1alpha1.MarsJob, opts v1.UpdateOptions) (*v1alpha1.MarsJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(marsjobsResource, "status", c.ns, marsJob), &v1alpha1.MarsJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MarsJob), err
}

// Delete takes name of the marsJob and deletes it. Returns an error if one occurs.
func (c *FakeMarsJobs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(marsjobsResource, c.ns, name), &v1alpha1.MarsJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMarsJobs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(marsjobsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MarsJobList{})
	return err
}

// Patch applies the patch and returns the patched marsJob.
func (c *FakeMarsJobs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MarsJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(marsjobsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MarsJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MarsJob), err
}
