# permissions for end users to view elasticbatchjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticbatchjob-viewer-role
rules:
- apiGroups:
  - inference.kubedl.io
  resources:
  - elasticbatchjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - inference.kubedl.io
  resources:
  - elasticbatchjobs/status
  verbs:
  - get
