# permissions for end users to edit elasticbatchjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elasticbatchjob-editor-role
rules:
- apiGroups:
  - inference.kubedl.io
  resources:
  - elasticbatchjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inference.kubedl.io
  resources:
  - elasticbatchjobs/status
  verbs:
  - get
