apiVersion: notebook.kubedl.io/v1alpha1
kind: Notebook
metadata:
  name: notebook-sample
spec:
  # Add fields here
  template:
    spec:
      containers:
        - name: notebook
          image: jupyter/tensorflow-notebook
          volumeMounts:
            - mountPath: "/workspace"
              name: "workspace"
          resources:
            limits:
              cpu: 2048m
              memory: 2Gi
            requests:
              cpu: 1024m
              memory: 1Gi
      volumes:
        - name: "workspace"
          hostPath:
            path: /tmp/data
            type: DirectoryOrCreate
