apiVersion: "training.kubedl.io/v1alpha1"
kind: "TFJob"
metadata:
  name: "tf-cache"
spec:
  cleanPodPolicy: None
  cacheBackend:
    name: test-cachebackend
    mountPath: "/data"   # mountPath is the path to which cached files are mounted to the container
  tfReplicaSpecs:
    Worker:
      replicas: 1 
      restartPolicy: Never
      template:
        spec:
          containers:
            - name: tensorflow
              image: kubedl/tf-mnist-with-summaries:1.0
              command:
                - "python"
                - "/var/tf_mnist/mnist_with_summaries.py"
                - "--log_dir=/train/logs"
                - "--data_dir=/data/mnist"  # dataset directory, equivalent to "mountPath + subdirName"
                - "--learning_rate=0.01"
                - "--batch_size=150"
              resources:
                limits:
                  cpu: 2048m
                  memory: 2Gi
                requests:
                  cpu: 1024m               
                  memory: 1Gi
