name: Generate Image Daily
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 22 * * *'
jobs:
  kubedl-controller-daily-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: |
          export IMAGE="kubedl/kubedl:daily"
          make docker-build
          make docker-push
  kubedl-dashboard-daily-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: |
          export IMAGE="kubedl/dashboard:daily"
          make dashboard-image-build
          make dashboard-image-push
