/*
Copyright 2021 The Alibaba Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ElasticDLJobListerExpansion allows custom methods to be added to
// ElasticDLJobLister.
type ElasticDLJobListerExpansion interface{}

// ElasticDLJobNamespaceListerExpansion allows custom methods to be added to
// ElasticDLJobNamespaceLister.
type ElasticDLJobNamespaceListerExpansion interface{}

// MPIJobListerExpansion allows custom methods to be added to
// MPIJobLister.
type MPIJobListerExpansion interface{}

// MPIJobNamespaceListerExpansion allows custom methods to be added to
// MPIJobNamespaceLister.
type MPIJobNamespaceListerExpansion interface{}

// MarsJobListerExpansion allows custom methods to be added to
// MarsJobLister.
type MarsJobListerExpansion interface{}

// MarsJobNamespaceListerExpansion allows custom methods to be added to
// MarsJobNamespaceLister.
type MarsJobNamespaceListerExpansion interface{}

// PyTorchJobListerExpansion allows custom methods to be added to
// PyTorchJobLister.
type PyTorchJobListerExpansion interface{}

// PyTorchJobNamespaceListerExpansion allows custom methods to be added to
// PyTorchJobNamespaceLister.
type PyTorchJobNamespaceListerExpansion interface{}

// TFJobListerExpansion allows custom methods to be added to
// TFJobLister.
type TFJobListerExpansion interface{}

// TFJobNamespaceListerExpansion allows custom methods to be added to
// TFJobNamespaceLister.
type TFJobNamespaceListerExpansion interface{}

// XDLJobListerExpansion allows custom methods to be added to
// XDLJobLister.
type XDLJobListerExpansion interface{}

// XDLJobNamespaceListerExpansion allows custom methods to be added to
// XDLJobNamespaceLister.
type XDLJobNamespaceListerExpansion interface{}

// XGBoostJobListerExpansion allows custom methods to be added to
// XGBoostJobLister.
type XGBoostJobListerExpansion interface{}

// XGBoostJobNamespaceListerExpansion allows custom methods to be added to
// XGBoostJobNamespaceLister.
type XGBoostJobNamespaceListerExpansion interface{}
